name: publisher_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.12.2
  flutter: ^3.44.2

dependencies:
  bloc: ^9.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2


  book_core:
    path: ../../packages/book_core
  book_exporters:
    path: ../../packages/book_exporters
  file_picker: ^11.0.2
  flutter_markdown_plus: ^1.0.7
  printing: ^5.15.0
dev_dependencies:
  bloc_lint: ^0.4.1
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.24
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
